apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-ca
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 30054
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-orderer
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 31010
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-org1peer1
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 30110
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-org2peer1
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 30210
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-org3peer1
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 30310
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blockchain-org4peer1
subsets:
  - addresses:
      - ip: 10.128.0.3
    ports:
      - port: 30410